config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'contact' => 'static_pages#contact'

  get 'about' => 'static_pages#about'

  get    'patients/login' => 'patient_session#new',                   as: :patient_login
  post   'patients/:id/create_inr' => 'inr_records#create',           as: :create_inr
  post   'patients/:id/issue_emergency' => 'patients#issue_emergency',as: :issue_emergency
  delete 'patients/:id/delete_inr/:inr_id' => 'inr_records#destroy',  as: :delete_inr

  get     'doctors/login'           => 'doctor_session#new',     as: :doctor_login
  post    'doctors/:id/add_patient' => 'doctors#add_patient',    as: :add_patient
  delete  'doctors/:id/delete_patient/:patient_id' => 'doctors#delete_patient', as: :remove_patient
  get     'doctors/:id/monitor_patient/:patient_id'             =>  'doctors#monitor_patient',      as: :monitor_patient
  get     'doctors/:id/initialize_patient/:patient_id'          =>  'patients#init',          as: :init_patient
  patch   'doctors/:id/initialize_patient/:patient_id'          =>  'patients#set_init',            as: :set_init_patient
  get     'doctors/:id/edit_prescriptions/:patient_id'          =>  'prescription_calendar#edit',   as: :edit_prescription_calendar
  patch   'doctors/:id/update_prescription/:prescription_id'    =>  'drug_prescriptions#update',    as: :update_prescription
  post    'doctors/:id/add_prescription/:patient_id'            =>  'drug_prescriptions#create',    as: :create_prescription
  delete  'doctors/:id/delete_prescription/:prescription_id'    =>  'drug_prescriptions#destroy',   as: :delete_prescription

  post   'login'         => 'sessions#create',      as: :login
  delete 'logout'         => 'sessions#destroy',    as: :logout
  resources :patients
  resources :doctors

  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	before_action :require_logout, only: :home

	def home
	end

	def contact
	end

	def about
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
   <div class="container theme-showcase" role="main">

      <div class="page-header">
          <h1>About HAPP</h1>
      </div>

      <div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators" >
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="/images/banner1.jpg" alt="Chania">
    </div>

    <div class="item">
      <img src="/images/banner2.jpg" alt="Chania">
    </div>

    <div class="item">
      <img src="/images/banner3.jpg" alt="Flower">
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>


      <div class="row">
        <div class="col-lg-12">
          <h2>HAPP - Your heart matters...</h2>
          <p style="font-size:120%;">Preventive healthcare is transforming the healthcare approach and gaining importance day by day. The most important reason for that is preventive healthcare is easier, more painless and less costly than regular treatment process after the diagnosis. Regarding these reasons preventive healthcare leads to social & economical improvement to the society.</p>
 
          <p style="font-size:120%;">A today preventive healthcare application mostly requires regular visits to doctors. These visits are time consuming for both patients and doctors, and patients generally cannot find that time to go and do that visits. In these visits doctors only cover the physical states and biological values that are not enough.</p>
 
          <p style="font-size:120%;">Just as health encompasses a variety of physical and mental states, so do disease and disability, which are affected by environmental factors, genetic predisposition, disease agents, and lifestyle choices. Doctors are not capable of covering all environmental factors, genetic predisposition, disease agents and lifestyle choices. So there is a need for using all these multiple data sources and evaluating these data with high accuracy to achieve correct diagnosis. Especially predictive diagnosis, which can lead early phase treatments and a perfect appliance of preventive healthcare.</p>
 
          <p style="font-size:120%;">This is the point where HAPP (Health Analysis & Prediction Program) comes in. HAPP is a cloud application which gathers patient related information from multiple sources, analyze that information and make predictions to achieve preventive healthcare. </p>
        </div>
      </div>

    </div> <!-- /container -->

app/views/static_pages/contact.html.erb
<style>
        #map {
          width: 450px;
          height: 300px;
        }
      </style>


    <div class="container">

<div class="row">
	<div class="col-md-6" align="center">  
		 <h1 >Contact us!</h1>
     <div id="map" style="margin-top: 50px;"></div>
      <script>
        function initMap() {
          var mapDiv = document.getElementById('map');
          var map = new google.maps.Map(mapDiv, {
            center: {lat: 39.8746147, lng: 32.7475962},
            zoom: 16
          });
        }
      </script>
      <script src="https://maps.googleapis.com/maps/api/js?callback=initMap" async defer></script>

      <p align="center">Bilkent University</p>
      <p align="center">Çankaya/Ankara</p>
      <p align="center">T: 123-456-7890</p>
      <p align="center">F: 123-456-7890</p>
      <p align="center">projecthealthapp@gmail.com</p>
      </div>

	<div class="col-md-6" align="center">  

      <h1 align="center" >Meet Our Team</h1>
       <div class="row" style="margin-top: 100px;">
            <div class="col-md-3">
               <img align="center" class="img-circle" src="/images/berkay.jpg" alt="Generic placeholder image" width="128" height="128">
              <h4>Berkay Çakır</h4>
              <p>Bilkent University CS/IV</p>
            </div>
            <div class="col-md-3">
               <img align="center" class="img-circle" src="/images/burak.jpg" alt="Generic placeholder image" width="128" height="128">
              <h4>Burak Özmen</h4>
              <p>Bilkent University CS/IV</p>
            </div>
            <div class="col-md-3">
               <img align="center" class="img-circle" src="/images/iso.jpg" alt="Generic placeholder image" width="128" height="128">
              <h4>İsmail Can Dereli</h4>
              <p>Bilkent University CS/IV</p>
            </div>
            <div class="col-md-3">
               <img align="center" class="img-circle" src="/images/umut.jpg" alt="Generic placeholder image" width="128" height="128">
              <h4>Umut Barış İşler</h4>
              <p>Bilkent University CS/IV</p>
            </div>
        </div>
      </div>
</div>

    </div> 

app/views/static_pages/home.html.erb
<div class="container">
	<div style="width: 80%; margin: 100px auto" class="row">
		<div class="col-md-6" align = "center">
          <%= image_tag("doctor.png", class:"img-circle", style:"background-color:white;")	%>
          <h2>Doctors</h2>
          <p>
          <%= link_to "Doctor Login", doctor_login_path, class:"btn btn-lg btn-primary", role:"button" %> 
           <p> <%= link_to "Create doctor account", new_doctor_path  %></p>
		  </p>
        </div>

		<div class="col-md-6" align = "center">
          <%= image_tag("patient.jpg", class:"img-circle", style:"background-color:white;")	%>
          <h2>Patients</h2>
          <p>
          <%= link_to "Patient Login", patient_login_path, class:"btn btn-lg btn-success", role:"button" %> 
          <p> <%= link_to "Create patient account", new_patient_path  %></p>
		  </p>
        </div>
	</div>
</div>