config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'contact' => 'static_pages#contact'

  get 'about' => 'static_pages#about'

  get    'patients/login' => 'patient_session#new',                   as: :patient_login
  post   'patients/:id/create_inr' => 'inr_records#create',           as: :create_inr
  post   'patients/:id/issue_emergency' => 'patients#issue_emergency',as: :issue_emergency
  delete 'patients/:id/delete_inr/:inr_id' => 'inr_records#destroy',  as: :delete_inr

  get     'doctors/login'           => 'doctor_session#new',     as: :doctor_login
  post    'doctors/:id/add_patient' => 'doctors#add_patient',    as: :add_patient
  delete  'doctors/:id/delete_patient/:patient_id' => 'doctors#delete_patient', as: :remove_patient
  get     'doctors/:id/monitor_patient/:patient_id'             =>  'doctors#monitor_patient',      as: :monitor_patient
  get     'doctors/:id/initialize_patient/:patient_id'          =>  'patients#init',          as: :init_patient
  patch   'doctors/:id/initialize_patient/:patient_id'          =>  'patients#set_init',            as: :set_init_patient
  get     'doctors/:id/edit_prescriptions/:patient_id'          =>  'prescription_calendar#edit',   as: :edit_prescription_calendar
  patch   'doctors/:id/update_prescription/:prescription_id'    =>  'drug_prescriptions#update',    as: :update_prescription
  post    'doctors/:id/add_prescription/:patient_id'            =>  'drug_prescriptions#create',    as: :create_prescription
  delete  'doctors/:id/delete_prescription/:prescription_id'    =>  'drug_prescriptions#destroy',   as: :delete_prescription

  post   'login'         => 'sessions#create',      as: :login
  delete 'logout'         => 'sessions#destroy',    as: :logout
  resources :patients
  resources :doctors

  

end

app/models/patient.rb
class Patient < ActiveRecord::Base
	has_secure_password
    has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>", :small => "30x30>" }, 
                                :url => "HAPP/avatars/patients/:id/:basename_:style.:extension", 
                                :path => "HAPP/avatars/patients/:id/:basename_:style.:extension",
                                :default_url => "avatar.png",
                                :convert_options => { :thumb => "-quality 75 -strip" }

    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

	enum risk: [:low, :high]
	enum desired_inr: ["2.5-3.5", "2.0-3.0"]
	enum therapy_state: [:daily, :weekly]

	belongs_to :doctor

	has_many :inr_records
	has_many :drug_prescriptions

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\-.]+\.[a-z]+\z/i
	validates  :email, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    allow_nil: true,
                    uniqueness: { case_sensitive: false }

    def fullname
    	return "#{name.capitalize} #{surname.capitalize}"
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
	include SessionsHelper
	before_action :require_login, only: [:show, :init, :set_init, :edit, :update]
	before_action :require_patient_login, only: [:show, :edit, :update]
	before_action :require_doctor_login, only: [:init, :set_init]
	before_action :require_patient_ownership, only: [:init, :set_init]


	def show
		@inr = InrRecord.new
		@inr_records = current_user.inr_records
		@patient = current_user
		@date = params[:month] ? Date.parse(params[:month].gsub('-', '/')) : Date.today
		@drug_prescriptions = @patient.drug_prescriptions
	end

	def new
		@patient = Patient.new
	end

	def create
		@patient = Patient.new(signup_params)
		if @patient.save
			log_in @patient, "patient"
			redirect_to @patient
		else
			flash[:danger] = "Account could not be created."
			render 'new'
		end
	end

	def init
		@patient = Patient.find(params[:patient_id])
	end

	def set_init
		@patient = Patient.find(params[:patient_id])
		if @patient.update_attributes(init_params)
			# success flash
			flash[:success] = "Patient has successfully initiated." 
			redirect_to monitor_patient_path(current_user, @patient)
		else
			# fail flash
			flash[:danger] = "Patient could not be initiated."
			redirect_to init_patient_path(current_user, @patient)
		end
	end

	def edit
		@patient = current_user
	end

	def destroy
	end

	def update
		@patient = current_user
		if  @patient.update_attributes(update_params)
			flash[:success] = "Your profile has been updated successfully."
	    	redirect_to edit_patient_path
	    else 
	    	flash[:danger]  = "Your profile could not be updated."
	    	redirect_to edit_patient_path
	    end
	end

	def issue_emergency
		patient = current_user
		if patient.doctor
			flash[:success] = "Emergency has been issued successfully."
			SendEmergencyMailJob.perform_later patient.doctor, patient
			redirect_to current_user
		else
			flash[:danger] = "You do not have a doctor."
			redirect_to current_user
		end
	end

	private
	def signup_params
		params.require(:patient).permit(:name, :surname, :email, :password, :password_confirmation)
	end

	private
	def update_params
		params.require(:patient).permit(:name, :surname, :email, :birthday, :password, :password_confirmation, :avatar)
	end

	private
	def init_params
		params.require(:patient).permit(:risk, :desired_inr, :initial_dose)
	end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_graph.html.erb
<h2> INR - Dosage Timeline </h2>
<div id="chart_div" style="width: 100%; height: 500px;"></div>

<script>
$(function () { 

	google.charts.load('current', {'packages':['corechart']});
	google.charts.setOnLoadCallback(drawVisualization);

	function drawVisualization() {
		// Some raw data (not necessarily accurate)
		var data = new google.visualization.DataTable();
		data.addColumn('string', 'Date');
		data.addColumn('number', 'Dosage');
		data.addColumn('number', 'INR');
		data.addRows(<%= DrugInr.generate_array(@patient) %>);

		var options = {
			vAxes: { 1: {title: 'Dose', format: '#.#', maxValue: 20}, 
			0: {title: 'INR',format: '#.#', minValue: -1, baselineColor:"#CCCCCC"} },
			hAxis: {title: 'Day'},
			seriesType: 'bars',
			bar: {
				groupWidth: 5
			},
			series: {
				0:{ type: "bars", targetAxisIndex: 1 },
				1:{ type: 'line', targetAxisIndex: 0}

			}
	};



var chart = new google.visualization.ComboChart(document.getElementById('chart_div'));
chart.draw(data, options);

}
});

</script>

app/views/patients/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-3">
    </div>
    <div class="col-xs-12 col-sm-6">
    <%= form_for @patient, url: patient_path(@patient) do |f| %>
    <%# form_for(:session, url: login_path, html: {class: "form-signin"}) do |f| %>
    <h2 class="form-signin-heading" style="text-transform: capitalize;"><%= current_user.name +  " " + current_user.surname %> - Profile Edit</h2>
    <label class="sr-only"> Name </label>
    <%= f.text_field :name, class: "form-control", placeholder: "Name", required: true %>
    <label class="sr-only"> Surname </label>
    <%= f.text_field :surname, class: "form-control", placeholder: "Surname", required: true %>
    <label class="sr-only"> Email </label>
    <%= f.email_field :email, class: "form-control", placeholder: "Email", required: true %>
    <label for="inputPassword" class="sr-only">Password</label>
    <%= f.password_field :password, class: "form-control", placeholder: "Password", required: true %>
    <label for="inputPassword" class="sr-only">Password Confirmation</label>
    <%= f.password_field :password, class: "form-control", placeholder: "Password Confirmation", required: true %>
    <%= f.file_field :avatar, class: "form-control", 'data-buttonText': "Find file" %>
    <%= f.submit "Update", class:"new-button btn btn-lg btn-primary btn-block"  %>
    <% end %>
    </div>
  </div>
</div>

<script>
$(":file").filestyle({buttonText: "Click here to select avatar"});
</script>

app/views/patients/init.html.erb
<div class="container">
   <div class="row">
   <div class="col-xs-12 col-sm-4"></div>
	  <div class="col-xs-12 col-sm-4">
	  		<table class="risk-table">
	  			<tr>
	  				<td class="risk-definition" align="center">
	  					<ul class="list-group">
		  				<p>+ Age >60 years old</p>
						<p>+ Impaired nutritional status or low BMI</p>
						<p>+ Congestive heart failure</p>
						<p>+ Liver disease (Child-Pugh Grade B/C)</p>
						<p>+ Taking medications known to increase warfarin activity or increase bleeding risk</p>
						<p>+ Recent major surgery or high risk of bleeding </p>
						</ul>
					</td>
	  				<td class="risk-name" align="center">
		  				High risk
	  				</td>
	  			</tr>
	  		</table>
			<%= form_for @patient, url: set_init_patient_path(current_user, @patient) do |f| %>
				<label> Risk </label>
				<%= f.select :risk,  Patient.risks.keys.to_a,{},{required: true,  class: "selectpicker form-control" , style: "display: inline-block!important; width:100%;"}%>

				<label> Desired INR </label>
				<%= f.select :desired_inr, Patient.desired_inrs.keys.to_a,{},{required: true, class: "selectpicker form-control" , style: "display: inline-block!important; width:100%;"} %>

				<label class="sr-only"> desired_inr </label>
				<%= f.number_field :initial_dose, :step => '0.5', required: true, class: "form-control"  %>


				<p> Suggestion: <span id="suggestion"><em>larger than 5mg, smaller than 10mg</em></span></p>
				<%= f.submit "Init", class:"new-button btn btn-lg btn-primary btn-block" %>
			<% end %>
		</div>
	</div>
</div>

app/views/patients/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-12 col-sm-4">
		</div>
		<div class="col-xs-12 col-sm-4">
  	<%= form_for @patient do |f| %>
  	<%= render 'shared/patient_error_messages' %>
  	<%# form_for(:session, url: login_path, html: {class: "form-signin"}) do |f| %>
  	<h2 class="form-signin-heading">Create patient account</h2>
  	<label class="sr-only"> Name </label>
  	<%= f.text_field :name, class: "form-control", placeholder: "Name", required: true %>
  	<label class="sr-only"> Surname </label>
  	<%= f.text_field :surname, class: "form-control", placeholder: "Surname", required: true %>
  	<label class="sr-only"> Email </label>
  	<%= f.email_field :email, class: "form-control", placeholder: "Email", required: true %>
  	<label for="inputPassword" class="sr-only">Password</label>
  	<%= f.password_field :password, class: "form-control", placeholder: "Password", required: true %>
  	<label for="inputPassword" class="sr-only">Password Confirmation</label>
  	<%= f.password_field :password, class: "form-control", placeholder: "Password Confirmation", required: true %>
  	<%= f.submit "Create my account", class:"new-button btn btn-lg btn-primary btn-block"  %>
  	<% end %>
  	</div>
	</div>
</div>

app/views/patients/show.html.erb
<style type="text/css">
  .form-control{
    width: 29%;
    display: inline-block;
  }
</style>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<div class="container">
  <div class="row">
    <div class="col-md-12" align="center">
      <h1>      <%= image_tag(@patient.avatar.url(:thumb), :style => "border-radius: 50%; height: 100px; width: 100px;" ) %>
        <%= @patient.fullname %> </h1>
    </div>
  </div>

    <div class="row">
      <div id="calendar" class="col-md-6">
        <h2 align="center"> Drug Prescription Calendar </h2>
        <h3 id="month">
          <%= link_to "<", :month => (@date.beginning_of_month-1).strftime("%Y-%m") %>
          <%=h @date.strftime("%B %Y") %>
          <%= link_to ">", :month => (@date.end_of_month+1).strftime("%Y-%m") %>
        </h3>
        <%= calendar_for @drug_prescriptions, :year => @date.year, :month => @date.month do |calendar| %>
        <%= calendar.head('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday') %>
        <%= calendar.day(:day_method => :date) do |date,drug_prescriptions| %>
        <%= date.day %>
        <ul>
          <% for drug_prescription in drug_prescriptions %>
          <li> <%= drug_prescription.dosage %> </li>
          <% end %>
        </ul>
        <% end %>
        <% end %>
      </div>

      <div class="col-md-6" align="center">
        <%= render 'patients/graph' %>
      </div>
      <div class="col-md-12">
        <h3>Add INR Record</h3>
        <%= form_for @inr, url: create_inr_path(current_user, @inr) do |f| %>
        <%= f.label :inr_value %>
        <%= f.number_field :inr_value, :step => '0.1', class: "form-control" %>
        <%= f.label :date %>
        <%= f.text_field :date, 'data-provide': 'datepicker', class: 'form-control datepicker' %> 
        <%= f.submit "Add INR Record", class: "btn btn-default", style: "margin-top: -4px;" %>
        <% end %>
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Value</th>
              <th>Date</th>
              <th></th>
            </tr>
          </thead>
          <% @inr_records.each do |ir| %>

          <tr>
            <td>  <%= "#{ir.inr_value} " %> </td>
            <td><%= "#{ir.date}" %></td>
            <td><%= link_to "Delete", delete_inr_path(current_user, ir), method: "delete" %></td>
          </tr>

          <% end %>
        </table>
      </div>


    </div>
  </div>