config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'contact' => 'static_pages#contact'

  get 'about' => 'static_pages#about'

  get    'patients/login' => 'patient_session#new',                   as: :patient_login
  post   'patients/:id/create_inr' => 'inr_records#create',           as: :create_inr
  post   'patients/:id/issue_emergency' => 'patients#issue_emergency',as: :issue_emergency
  delete 'patients/:id/delete_inr/:inr_id' => 'inr_records#destroy',  as: :delete_inr

  get     'doctors/login'           => 'doctor_session#new',     as: :doctor_login
  post    'doctors/:id/add_patient' => 'doctors#add_patient',    as: :add_patient
  delete  'doctors/:id/delete_patient/:patient_id' => 'doctors#delete_patient', as: :remove_patient
  get     'doctors/:id/monitor_patient/:patient_id'             =>  'doctors#monitor_patient',      as: :monitor_patient
  get     'doctors/:id/initialize_patient/:patient_id'          =>  'patients#init',          as: :init_patient
  patch   'doctors/:id/initialize_patient/:patient_id'          =>  'patients#set_init',            as: :set_init_patient
  get     'doctors/:id/edit_prescriptions/:patient_id'          =>  'prescription_calendar#edit',   as: :edit_prescription_calendar
  patch   'doctors/:id/update_prescription/:prescription_id'    =>  'drug_prescriptions#update',    as: :update_prescription
  post    'doctors/:id/add_prescription/:patient_id'            =>  'drug_prescriptions#create',    as: :create_prescription
  delete  'doctors/:id/delete_prescription/:prescription_id'    =>  'drug_prescriptions#destroy',   as: :delete_prescription

  post   'login'         => 'sessions#create',      as: :login
  delete 'logout'         => 'sessions#destroy',    as: :logout
  resources :patients
  resources :doctors

  

end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
	has_secure_password
    has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>", :small => "30x30>" }, 
                                :url => "HAPP/avatars/doctors/:id/:basename_:style.:extension", 
                                :path => "HAPP/avatars/doctors/:id/:basename_:style.:extension",
                                :default_url => "avatar.png",
                                :convert_options => { :thumb => "-quality 75 -strip" }
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

	has_many :patients

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\-.]+\.[a-z]+\z/i
	validates  :email, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    allow_nil: true,
                    uniqueness: { case_sensitive: false }

    def fullname
    	return "#{name.capitalize} #{surname.capitalize}"
    end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
	before_action :require_login, only: [:show, :update, :edit, :add_patient, :delete_patient, :monitor_patient]
	before_action :require_init, only: :monitor_patient
	before_action :require_doctor_login, only: [:show, :edit, :update, :add_patient, :delete_patient, :monitor_patient]
	before_action :require_patient_ownership, only: [:delete_patient, :monitor_patient]


	def show
	end

	# GET 'doctors/new'
	def new
		@doctor = Doctor.new
	end

	# POST 'doctors'
	def create
		@doctor = Doctor.new(signup_params)
		if @doctor.save 
			log_in @doctor, "doctor"
			redirect_to @doctor
		else
			flash[:danger] = "Account could not be created."
			render 'new'
		end
	end

	# GET 'doctors/:id/edit'
	def edit
		@doctor = current_user
	end

	def destroy
	end

	# PATCH 'doctors/:id'
	def update
		@doctor = current_user
		if  @doctor.update_attributes(update_params)
			flash[:success] = "Your profile has been updated successfully."
	    	redirect_to edit_doctor_path
	    else
	    	flash[:danger] = "Your profile could not be updated."
	    	redirect_to edit_doctor_path
	    end
	end

	# POST 'doctors/:id/add_patient'
	def add_patient
		patient = Patient.find_by_email(params[:patient][:email])
		if patient
			if patient.doctor
				# zaten bir doktoru var diye flash ver
				flash[:danger] = "This patient is already assigned to a doctor."
				redirect_to current_user
			else
				flash[:success] = "Patient is assigned to you successfully."
				patient.doctor = current_user
				patient.save
				redirect_to current_user
			end
		else
			# böyle bir hasta yok diye 
			redirect_to current_user
		end
	end

	def delete_patient
		patient = Patient.find(params[:patient_id])
		@doctor = current_user
		@doctor.patients.delete(patient)
		redirect_to current_user
	end

	# GET 'doctors/:id/monitor_patient/:patient_id'
	def monitor_patient
		@patient = Patient.find(params[:patient_id])
		@drug_prescriptions = @patient.drug_prescriptions
		@date = params[:month] ? Date.parse(params[:month].gsub('-', '/')) : Date.today
		@drug = DrugPrescription.new
	end

	private
	def signup_params
		params.require(:doctor).permit(:name, :surname, :email, :password, :password_confirmation)
	end

	private
	def update_params
		params.require(:doctor).permit(:name, :surname, :email, :birthday, :password, :password_confirmation, :avatar)
	end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-12 col-sm-3">
		</div>
		<div class="col-xs-12 col-sm-6">
  	<%= form_for @doctor, url: doctor_path(@doctor) do |f| %>
  	<%# form_for(:session, url: login_path, html: {class: "form-signin"}) do |f| %>
  	<h2 class="form-signin-heading" style="text-transform: capitalize;"><%= current_user.name +  " " + current_user.surname %> - Profile Edit</h2>
  	<label class="sr-only"> Name </label>
  	<%= f.text_field :name, class: "form-control", placeholder: "Name", required: true %>
  	<label class="sr-only"> Surname </label>
  	<%= f.text_field :surname, class: "form-control", placeholder: "Surname", required: true %>
  	<label class="sr-only"> Email </label>
  	<%= f.email_field :email, class: "form-control", placeholder: "Email", required: true %>
    <label for="inputPassword" class="sr-only">Password</label>
  	<%= f.password_field :password, class: "form-control", placeholder: "Password", required: true %>
  	<label for="inputPassword" class="sr-only">Password Confirmation</label>
  	<%= f.password_field :password, class: "form-control", placeholder: "Password Confirmation", required: true %>
    <%= f.file_field :avatar, class: "form-control", 'data-buttonText': "Find file" %>
  	<%= f.submit "Update", class:"new-button btn btn-lg btn-primary btn-block"  %>
  	<% end %>
  	</div>
	</div>
</div>

<script>
$(":file").filestyle({buttonText: "Click here to select avatar"});
</script>

app/views/doctors/monitor_patient.html.erb
<style type="text/css">
	.messages-scroll{
		width: 100%;
		height: 50px;
		overflow: auto;
	}
</style>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<div class="container">
	<div class="row">
		<div class="col-md-12" align="center">
			<h1> 			<%= image_tag(@patient.avatar.url(:thumb), :style => "border-radius: 50%; height: 100px; width: 100px;" ) %>
<%= @patient.fullname %> </h1>
		</div>
	</div>
	<div class="row">
		<div class="col-md-6" align="center">
			<%= render 'patients/graph' %>
		</div>
		<div id="calendar" class="col-md-6">
			<h2 id="month">
				<%= link_to "<", :month => (@date.beginning_of_month-1).strftime("%Y-%m") %>
				<%=h @date.strftime("%B %Y") %>
				<%= link_to ">", :month => (@date.end_of_month+1).strftime("%Y-%m") %>
			</h2>
			<%= calendar_for @drug_prescriptions, :year => @date.year, :month => @date.month do |calendar| %>
			<%= calendar.head('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday') %>
			<%= calendar.day(:day_method => :date) do |date,drug_prescriptions| %>
			<%= date.day %>
			<ul>
				<% for drug_prescription in drug_prescriptions %>
				<li> <%= drug_prescription.dosage %> </li>
				<% end %>
			</ul>
			<% end %>
			<% end %>

			<!-- takvim edit butonu -->
			<%= link_to "Edit Calendar", edit_prescription_calendar_path(current_user, @patient), class: "btn btn-default", style: "width: 100%" %>
			<!-- takvim edit butonu -->
		</div>
	</div>

	<!-- RECOMMENDATION -->
	<div class="col-md-6">
		<hr/>
		<div class="panel with-nav-tabs panel-default">
			<div class="panel-heading">
				<ul class="nav nav-tabs">
					<li class="active"><a href="#tab1default" data-toggle="tab">Recommendation</a></li>
				</ul>
			</div>
			<div class="panel-body">
				<div class="tab-content">
					<div class="tab-pane fade active in" id="tab1default">
						<%= DoseAdvisor.advise(@patient) %>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- RECOMMENDATION -->
	<div class="col-md-12">
		<!-- HASTA PRESCRIPTION EKLEME ŞEYSİ -->
		<p>Add Prescription</p>
		<%= form_for @drug, url: create_prescription_path(current_user, @patient) do |f| %>
		<%= f.label :dosage %>
		<%= f.number_field :dosage, :step => '0.5', required: true %>
		<%= f.label :date %>
		<%= f.text_field :date, 'data-provide': 'datepicker', class: 'datepicker', required: true %> 
		<%= f.submit "Add Drug Prescription", class: "btn btn-default" %>
		<% end %>
		<!-- HASTA PRESCRIPTION EKLEME ŞEYSİ -->
		<!-- HASTA PRESCRIPTIONS -->
		<div class="col-md-12">
			<hr/>
			<table class="table table-hover">
				<thead>
					<tr>
						<th>Value</th>
						<th>Date</th>
						<th></th>
					</tr>
				</thead>
				<% @drug_prescriptions.each do |dp| %>
				<tr>
					<td>  <%= "#{dp.dosage} " %> </td>
					<td><%= "#{dp.date}" %></td>
					<td><%= link_to "Delete", delete_prescription_path(current_user, dp), method: "delete" %> </td>
				</tr>
				<% end %>
			</table>
		</div>
		<!-- HASTA PRESCRIPTIONS -->


	</div>
</div>
</div>

app/views/doctors/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-12 col-sm-4">
		</div>
		<div class="col-xs-12 col-sm-4">
  	<%= form_for @doctor do |f| %>
  	<%= render 'shared/doctor_error_messages' %>
  	<%# form_for(:session, url: login_path, html: {class: "form-signin"}) do |f| %>
  	<h2 class="form-signin-heading">Create doctor account</h2>
  	<label class="sr-only"> Name </label>
  	<%= f.text_field :name, class: "form-control", placeholder: "Name", required: true %>
  	<label class="sr-only"> Surname </label>
  	<%= f.text_field :surname, class: "form-control", placeholder: "Surname", required: true %>
  	<label class="sr-only"> Email </label>
  	<%= f.email_field :email, class: "form-control", placeholder: "Email", required: true %>
  	<label for="inputPassword" class="sr-only">Password</label>
  	<%= f.password_field :password, class: "form-control", placeholder: "Password", required: true %>
  	<label for="inputPassword" class="sr-only">Password Confirmation</label>
  	<%= f.password_field :password, class: "form-control", placeholder: "Password Confirmation", required: true %>
  	<%= f.submit "Create my account", class:"new-button btn btn-lg btn-primary btn-block"  %>
  	<% end %>
  	</div>
	</div>
</div>

app/views/doctors/show.html.erb
<div class="container">
   <div class="row">
    <div class="col-md-12" align="center">
      <h1>      <%= image_tag(current_user.avatar.url(:thumb), :style => "border-radius: 50%; height: 100px; width: 100px;" ) %>
        <%= current_user.fullname %> </h1>
    </div>
  </div>
   <div class="row">
      <div class="col-md-2" align="center">
      </div>
      <div class="col-md-8">
         <%= form_for(:patient, url: add_patient_path) do |f| %>
         <%= f.select :email, options_for_select(Patient.all.collect{|x| [x.fullname, x.email]}), {}, {required: true,  class: "selectpicker form-control", style: "display: inline-block!important; width:70%;"}%>
         <%= f.submit "Add patient", class: "btn btn-default", style: "margin-top: -4px;" %>
         <% end %>
         <table class="table table-hover user-list">
            <% current_user.patients.each do |p| %>
            <tr>
               <td style="width: 50px;">
               <%= link_to image_tag(p.avatar.url(:thumb), :style => "border-radius: 50%; height: 28px; width: 31px;" ), monitor_patient_path(current_user, p) %>
               <td><%= link_to p.fullname, monitor_patient_path(current_user, p) %></td>
               <td><%= link_to "Delete", remove_patient_path(current_user, p), method: "delete" %> </td>
            </tr>
            <% end %>
         </table>
      </div>
      <div class="col-md-2" align="center">
      </div>
   </div>
</div>