config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'contact' => 'static_pages#contact'

  get 'about' => 'static_pages#about'

  get    'patients/login' => 'patient_session#new',                   as: :patient_login
  post   'patients/:id/create_inr' => 'inr_records#create',           as: :create_inr
  post   'patients/:id/issue_emergency' => 'patients#issue_emergency',as: :issue_emergency
  delete 'patients/:id/delete_inr/:inr_id' => 'inr_records#destroy',  as: :delete_inr

  get     'doctors/login'           => 'doctor_session#new',     as: :doctor_login
  post    'doctors/:id/add_patient' => 'doctors#add_patient',    as: :add_patient
  delete  'doctors/:id/delete_patient/:patient_id' => 'doctors#delete_patient', as: :remove_patient
  get     'doctors/:id/monitor_patient/:patient_id'             =>  'doctors#monitor_patient',      as: :monitor_patient
  get     'doctors/:id/initialize_patient/:patient_id'          =>  'patients#init',          as: :init_patient
  patch   'doctors/:id/initialize_patient/:patient_id'          =>  'patients#set_init',            as: :set_init_patient
  get     'doctors/:id/edit_prescriptions/:patient_id'          =>  'prescription_calendar#edit',   as: :edit_prescription_calendar
  patch   'doctors/:id/update_prescription/:prescription_id'    =>  'drug_prescriptions#update',    as: :update_prescription
  post    'doctors/:id/add_prescription/:patient_id'            =>  'drug_prescriptions#create',    as: :create_prescription
  delete  'doctors/:id/delete_prescription/:prescription_id'    =>  'drug_prescriptions#destroy',   as: :delete_prescription

  post   'login'         => 'sessions#create',      as: :login
  delete 'logout'         => 'sessions#destroy',    as: :logout
  resources :patients
  resources :doctors

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HAPP</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <link href='https://fonts.googleapis.com/css?family=Work+Sans' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/css/bootstrap-select.min.css">
  <%= csrf_meta_tags %>
</head>
<body>
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <img src="/images/logo.png" style="margin">

        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="/">Home</a></li>
            <li><a href="/about">About</a></li>
            <li><a href="/contact">Contact</a></li>
            <% if session[:user_type] == 'patient' %>
              <li><%= link_to "EMERGENCY", issue_emergency_path(current_user), method: "post", class: "emergency" %></li>
            <% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
              <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <% if(current_user != nil) %>
                <%= image_tag(current_user.avatar.url(:thumb),  :style => "border-radius: 50%; height: 28px; width: 31px;" )%> <%= current_user.fullname[0,20] %> 
               <% end %>
                <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li>
                  <% if session[:user_type] == 'patient' %>
                    <%= link_to_if(session[:user_type] == 'patient', "Edit Profile", edit_patient_path(current_user.id)) %>
                  <% elsif session[:user_type] == 'doctor' %>
                    <%= link_to_if(session[:user_type] == 'doctor', "Edit Profile", edit_doctor_path(current_user.id)) %>
                  <% end %>
                </li>  
                <li>
                  <%= link_to "Log Out", logout_path, method: "delete" %> 
                </li>  
              </ul>
              </li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>


<%= yield %>

</body>
</html>